# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2020 Ambarella International LP

obj-y	+= pinmux.o rct.o common.o early_print.o dt-setup.o gic.o
obj-y	+= secure/ed25519/curve25519.o secure/auth.o
obj-$(CONFIG_ARCH_AMBARELLA_S6LM)	+= s6lm/
obj-$(CONFIG_ARCH_AMBARELLA_CV22)	+= cv22/
obj-$(CONFIG_ARCH_AMBARELLA_CV25)	+= cv25/
obj-$(CONFIG_ARCH_AMBARELLA_CV28)	+= cv28/
obj-$(CONFIG_ARCH_AMBARELLA_CV5)	+= cv5/
obj-$(CONFIG_ARCH_AMBARELLA_CV72)	+= cv72/
obj-$(CONFIG_ARCH_AMBARELLA_CV3)	+= cv3/
obj-$(CONFIG_ARCH_AMBARELLA_CV75)	+= cv75/
obj-$(CONFIG_ARCH_AMBARELLA_N1_655)	+= n1_655/
obj-$(CONFIG_ARCH_AMBARELLA_CV7)	+= cv7/
