# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2020 Ambarella International LP

obj-y	+= pinmux.o rct.o common.o early_print.o dt-setup.o
obj-$(CONFIG_ARCH_AMBARELLA_S6LM)	+= s6lm/
obj-$(CONFIG_ARCH_AMBARELLA_CV25)	+= cv25/
obj-$(CONFIG_ARCH_AMBARELLA_CV28)	+= cv28/
obj-$(CONFIG_ARCH_AMBARELLA_CV5)	+= cv5/
